### PR TITLE
Add security and privacy considerations

### PR DESCRIPTION
**Pull request by mattgarrish**
May not stand up to review, but here's some starter prose.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/53.html" title="Last updated on Sep 4, 2019, 3:50 PM UTC (b0c2959)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/53/356247f...b0c2959.html" title="Last updated on Sep 4, 2019, 3:50 PM UTC (b0c2959)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
I think it is a good start to have this, but we may have to consider more text as for the specific terms that are used and proposed by this spec. Does the inclusion of personal data (name, URL-s, identifiers) come as a privacy risk? Although I do not think that, at the end of the day, it does, the fact that we do think about it is important.

One way of considering it to see if there are privacy related consideration in schema.org that we can simply refer to (after all, we do not have extra terms in this area.)

**Comment by mattgarrish** [comment]
I've added a bullet list with some additional considerations. There are lots of possible security considerations for an actual format, but I can't think of what else to say at this level. Hopefully others will chime in.

I can't find anything about schema.org and security. As a pure vocabulary, it's probably not a concern how people expose their information.

**Comment by iherman** [comment]
It now reads a bit funny... the first sentence says that we have nothing to say, and then we list some privacy and security considerations later in the same section...

**Comment by mattgarrish** [comment]
Sure, ending off with a punt on specifics probably makes more sense now. I just pushed a minor reformulation to that end.

**Pull request merged**
