### PR TITLE
Remove the inDirection property

### LINKED ISSUE #48: Need for both inDirection and readingProgression
Per the discussion in PR #47, there are questions about these two properties and potential overlaps between them.

- `inDirection` claims to specify the text direction for placing menus, etc., while
- `readingProgression` claims to specify resource direction for placing menus, etc.

Both define `ltr` and `rtl` as there expected values, with `readingProgression` having a default of `ltr` and `inDirection` having no default. Do we need both?

### PR DESCRIPTION
**Pull request by mattgarrish**
Fixes #48.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/52.html" title="Last updated on Sep 2, 2019, 12:59 PM UTC (a089b21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/52/356247f...a089b21.html" title="Last updated on Sep 2, 2019, 12:59 PM UTC (a089b21)">Diff</a>

### CODE REVIEW

**Comment by llemeurfr** [comment]
The updated text lacks mention of the possibility of multiple languages for the publication and the use of the first language in the sequence as "primary" language (on which decisions will be taken for UI details).

**Comment by iherman** [comment]
@llemeurfr : I believe the text you are looking for is in: 

https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/52.html#language-and-dir

Or do I misunderstand you?

**Comment by mattgarrish** [comment]
We expanded `inLanguage` to an array in the last PR. From the section Ivan cites:

> A digital publication has at least one natural language
> ...
> Required Value One or more language codes as defined in [bcp47]
> ...
> If a user agent requires a primary language for the publication and more than one language is specified, the first entry in the inLanguage array MUST be recognized as the primary.

**Comment by llemeurfr** [comment]
That's right, I didn't spot the "at least" in the first sentence and the notion of "primary" clearly expressed. My bad. The section is fine!

**Pull request merged**
